export const CODIGO_DUPLICADO_CRM = 'DUP_CRM001';
export const CODIGO_NO_EXISTE_CRM = 'NOEXIST_CRM001';
export const CODIGO_ERROR_ALTA_CRM = 'ALTA_CRM001';
export const CODIGO_ERROR_ACTUALIZAR_CRM = 'UPD_CRM001';
export const CODIGO_ERROR_ALTA_SERVICIO_CRM = 'SERV_ALTA_CRM001';
export const CODIGO_ERROR_ACTUALIZAR_SERVICIO_CRM = 'SERV_UPD_CRM001';
